/* ============================================================================
   Tend - facts.js
   ----------------------------------------------------------------------------
   One fun fact a day, at the top of the page.

   All 365 are about animals, plants or the ocean. The app is a garden and a
   reef, so the fact of the day belongs to the same world - and a themed set is
   easier to keep interesting than a general one, which drifts into trivia about
   word origins and the Eiffel Tower.

   They are ordered so no more than two of the same kind land on consecutive
   days: a week reads as a mix rather than a run of birds. Each one also has to
   stand alone, since the shuffle means the fact you read yesterday is not the
   one before it in this array.

   Picked by the day of the year, so it loops once a year and everybody signed
   in sees the same one on the same date - which is the point: it is something
   to mention to somebody, not a private random draw. A random pick would also
   repeat within a week often enough to be noticeable, and would change every
   time the page re-rendered.

   Leap years get 366 days; day 366 falls back to the first fact rather than
   leaving a gap. Adding more facts is safe - the index wraps on the array's own
   length - but do not reorder them if you want the same date to keep its fact.
   ========================================================================= */

const Facts = (function () {
  'use strict';

  const FACTS = [
    "Glow-worms are not worms. They are beetle larvae, or wingless adult females.",
    "Dogs sniff with each nostril separately, which helps them tell which direction a smell came from.",
    "Lavender, mint, basil, rosemary and sage are all in the same plant family.",
    "Australia has more kangaroos than people.",
    "Manatees are more closely related to elephants than to any other sea creature.",
    "Moss has no roots. It takes water in through its leaves.",
    "An ostrich's eye is bigger than its brain.",
    "A salamander can regenerate a limb perfectly, several times over.",
    "Parrotfish chew coral and excrete sand. Much of a tropical white beach passed through one.",
    "Dock leaves growing near nettles is a coincidence of habitat, not nature providing a remedy.",
    "A moth was the first computer bug, found stuck in a relay in 1947 and taped into the logbook.",
    "Eels from Europe and America both breed in the Sargasso Sea, and nobody has ever seen them do it.",
    "A starfish can regrow an entire body from one arm, provided part of the central disc goes with it.",
    "Naked mole rats are almost immune to cancer and feel no pain from acid or chilli.",
    "A group of hedgehogs is called a prickle.",
    "Ocean currents move heat around the planet on a loop that takes about a thousand years to complete.",
    "Leafcutter ants do not eat the leaves. They feed them to a fungus, and eat that.",
    "The average bed contains millions of dust mites, which eat shed skin.",
    "Emperor penguins can dive over 500 metres deep and stay under for more than twenty minutes.",
    "Elephants are one of the few animals that cannot jump.",
    "A single aspen colony in Utah, called Pando, is one organism connected underground and may be tens of thousands of years old.",
    "A grizzly can smell a carcass from over 20km away.",
    "Half the oxygen you breathe comes from the ocean, made by plankton.",
    "Ginkgo biloba has barely changed in 200 million years and survives now mostly because people plant it.",
    "A giraffe's tongue is dark blue-purple, thought to protect it from sunburn while feeding.",
    "More people have been to space than to the deepest point of the ocean.",
    "A polar bear's skin is black under its transparent fur.",
    "Bees communicate the direction and distance of flowers by dancing in a figure of eight.",
    "A single brown bat can eat over a thousand mosquitoes in an hour.",
    "There is a species of shark, the Greenland shark, that does not reach maturity until around 150 years old.",
    "A rattlesnake's rattle is made of interlocking segments of keratin, adding one at each moult.",
    "Pitcher plants digest insects that drown in their fluid, and some host mosquito larvae that live in it safely.",
    "Horseshoe crabs have survived five mass extinctions largely unchanged.",
    "Ants do not have lungs. Oxygen enters through tiny holes along the body.",
    "Pandas have a wrist bone that works as a sixth digit, for gripping bamboo.",
    "Reindeer eyes change colour between summer and winter, from gold to blue.",
    "Grey whales make one of the longest migrations of any mammal, up to 20,000km a year.",
    "The heart of a hummingbird can beat over 1,200 times a minute in flight.",
    "Coffee was banned at various times in Mecca, Italy and Sweden as a dangerous stimulant.",
    "Sharks lose and regrow thousands of teeth over a lifetime.",
    "The oldest known recipe is for beer, on a Sumerian tablet nearly 4,000 years old.",
    "Fresh cranberries bounce, which is how they are sorted for quality.",
    "Dragonflies were once enormous. Fossils show wingspans of 70cm, when the air held more oxygen.",
    "Glass sponges build skeletons of silica and some are thought to live for millennia.",
    "Kangaroos cannot walk backwards.",
    "Fish can drown, if the water lacks oxygen or their gills are damaged.",
    "Bananas are harvested green and ripened with ethylene gas.",
    "A snail can sleep for up to three years.",
    "Some parrotfish sleep inside a cocoon of mucus they spin each night, which masks their scent.",
    "A chameleon's tongue can extend twice its body length in about a hundredth of a second.",
    "The oldest seed successfully germinated was a date palm about 2,000 years old, recovered in Israel.",
    "Wombats produce cube-shaped droppings, which they stack to mark territory without them rolling away.",
    "The ocean contains around 20 million tonnes of dissolved gold, too dilute to extract.",
    "Humans share roughly 60% of their DNA with bananas.",
    "The word 'muscle' comes from the Latin for little mouse, because a flexing bicep looked like one moving under the skin.",
    "A shrimp-like creature called the Antarctic krill may be the most abundant animal species on Earth by weight.",
    "A ladybird can eat 5,000 aphids in its lifetime.",
    "Cashews grow attached to the bottom of a fruit called a cashew apple.",
    "Snakes hear through their jawbones, picking up vibrations from the ground.",
    "Walrus tusks are elongated canine teeth, used to haul the animal onto ice.",
    "Crows can make and use tools, and can pass the knowledge to other crows.",
    "Some orchids produce no chlorophyll at all and live entirely off fungi.",
    "Bears do not truly hibernate. Their temperature drops only slightly and they can wake quickly.",
    "Neptune has been observed for less than one of its years. It takes 165 Earth years to orbit the Sun.",
    "An apple seed grown from a pip will not produce the same variety. Every named apple is a clone, grafted.",
    "Slugs have four noses.",
    "A giant Pacific octopus can squeeze through any gap larger than its beak, the only hard part of its body.",
    "Scorpions glow bright blue-green under ultraviolet light, and nobody is sure why.",
    "A eucalyptus tree can shed whole branches in drought, a habit that earned some the name widow-maker.",
    "Blue whale calves gain around 90kg a day on their mother's milk.",
    "There are more chickens on Earth than any other bird.",
    "Most fig species depend on one specific wasp species, and the wasp on that fig - neither survives without the other.",
    "Crocodiles have survived essentially unchanged since before the dinosaurs died out.",
    "A barnacle's glue is being studied as a surgical adhesive because it sets underwater.",
    "Platypuses hunt with their eyes shut, detecting electrical signals from prey with their bill.",
    "The pineapple plant flowers once, fruits once, and then produces offshoots and dies.",
    "Sea urchins walk on hundreds of tiny tube feet, and their teeth self-sharpen.",
    "A capybara will let almost any other animal sit on it, and often does.",
    "The world's smallest flowering plant is a watermeal, small enough that a dozen fit on a fingernail.",
    "Cats cannot taste sweetness. The gene for the receptor does not work in them.",
    "Horseshoe crabs are more closely related to spiders than to crabs.",
    "Tigers have striped skin as well as striped fur.",
    "The first oranges from Southeast Asia were tangerine-pomelo hybrids, and were green.",
    "Sea otters hold hands while sleeping so they do not drift apart.",
    "The oldest known animal cave painting is over 40,000 years old, in Indonesia.",
    "Charles Darwin's last book was about earthworms, and he considered them among the most important animals on Earth.",
    "The inventor of the frisbee was turned into a frisbee. Walter Morrison's ashes were moulded into one after he died.",
    "A narwhal's tusk is a tooth, spiralling out through its upper lip, and it can grow nearly three metres long.",
    "Koalas have fingerprints so similar to ours that they have confused crime scenes.",
    "Fungal networks under a forest can span several square kilometres and connect hundreds of trees.",
    "Mount Everest is not the tallest mountain from base to peak. Mauna Kea is, measured from the sea floor.",
    "Giraffes sleep around 30 minutes a day, usually in short bursts standing up.",
    "Komodo dragons can detect carrion from several kilometres away using their forked tongue.",
    "Coral bleaching is the animal expelling those algae under stress, losing both colour and food supply.",
    "Some species of ant farm fungus, keeping gardens underground for food.",
    "Pigs cannot look up at the sky easily, because of the structure of their neck.",
    "Some deep sea fish have no swim bladder, because at that pressure it would be useless.",
    "Goldfish have far better memories than the three-second myth suggests - months, in experiments.",
    "There is a species of orchid that mimics a female wasp closely enough that males try to mate with it.",
    "Ostriches can run at about 70km/h and cannot fly.",
    "Some corals fluoresce, glowing green and red under ultraviolet light.",
    "The Venus flytrap counts. It needs two triggers within about twenty seconds before it closes.",
    "An African grey parrot named Alex learned over a hundred words and asked what colour he was.",
    "Sea cucumbers can eject their internal organs to distract predators, then regrow them.",
    "Termite mounds are air-conditioned by design, with chimneys that drive a constant draught.",
    "An elephant's trunk can pick up a single blade of grass or lift several hundred kilograms.",
    "Armadillos always give birth to identical quadruplets, from a single egg.",
    "Jellyfish have no bones, blood or brain, and are about 95% water.",
    "Tomatoes were once feared in Europe as poisonous, partly because acidic juice leached lead from pewter plates.",
    "Sloths move so slowly that algae grows in their fur, which helps camouflage them.",
    "Dolphins have names for each other - signature whistles they answer to.",
    "Cheetahs cannot roar. They chirp, and the sound carries surprisingly far.",
    "Penicillin was discovered when a mould drifted onto a bacterial culture and cleared it.",
    "Worker bees change jobs with age: cleaning, nursing, building, guarding, and only then foraging.",
    "Narwhals were the source of the unicorn horn trade in medieval Europe.",
    "Wombats can run at about 40km/h in short bursts.",
    "Mother trees preferentially feed their own offspring through those fungal connections.",
    "Octopuses have three hearts. Two pump blood to the gills, and the third pumps it to the rest of the body.",
    "Vampire bats share blood meals with hungry roost-mates, and remember who shared with them.",
    "Lichen is two organisms living as one: a fungus and an alga, or sometimes a cyanobacterium.",
    "The longest recorded flight of a chicken is thirteen seconds.",
    "The Great Barrier Reef is the largest structure made by living organisms on Earth.",
    "Frogs absorb water through their skin rather than drinking it.",
    "Pandas are carnivores by digestive system but eat almost nothing but bamboo, so they must eat for hours a day.",
    "Tortoises can live well past 150, and some have outlived the people who recorded their hatching.",
    "Arctic terns migrate from pole to pole and see more daylight than any other animal.",
    "A truffle is a fungus that fruits underground and relies on animals digging it up to spread spores.",
    "Elephants greet each other after time apart with a ceremony of rumbles, touching and spinning.",
    "Greenland sharks can live for centuries. One was estimated at around 400 years old.",
    "Male platypuses have a venomous spur on the hind leg.",
    "Rice is grown in flooded fields partly because the water suppresses weeds that cannot tolerate it.",
    "Sea turtles return to the beach where they hatched to lay their own eggs, sometimes decades later.",
    "Army ants build bridges out of their own bodies, and the bridge dismantles itself once traffic stops.",
    "Honeybees can recognise individual human faces.",
    "The Sahara was green grassland with lakes and hippos around 6,000 years ago.",
    "A blue whale's tongue can weigh as much as an elephant.",
    "Parrots can outlive their owners, with some macaws reaching eighty.",
    "The Pacific Ocean is wider than the Moon's diameter by a factor of about forty.",
    "A fig is not a fruit but an inverted flower, pollinated from the inside by a tiny wasp.",
    "A hippo cannot actually swim. It walks and pushes off the bottom.",
    "An ant colony's collective decisions emerge with no ant knowing the plan.",
    "Mangrove trees filter salt at their roots and can excrete the rest through their leaves.",
    "Grafting means most apple trees of a variety are, genetically, the same tree from centuries ago.",
    "Cats spend around 70% of their lives asleep.",
    "Some turtles can breathe through their backsides, absorbing oxygen through the cloaca.",
    "There is a village in India where the bridges are grown, not built, from living tree roots.",
    "The platypus is one of only five mammal species that lay eggs.",
    "A crocodile cannot stick its tongue out.",
    "Coral is an animal that farms algae inside its own cells and gets most of its food from them.",
    "Bamboo is a grass, and some species grow nearly a metre in a single day.",
    "Wolves howl in different pitches, which makes a small pack sound much larger.",
    "The pistol shrimp snaps its claw so fast it creates a bubble that collapses with a flash of light.",
    "A beaver dam in Canada is long enough to be seen from orbit, over 800 metres.",
    "Bananas are slightly radioactive, because of the potassium in them.",
    "Spiders' silk comes in several types, and an orb weaver may use four or five in one web.",
    "A box jellyfish has 24 eyes, some of which form images, despite having no brain.",
    "Wild almonds are poisonous. A single mutation made the edible ones possible.",
    "A crocodile's jaw closes with enormous force but opens so weakly that a hand can hold it shut.",
    "Honey never spoils. Jars found in Egyptian tombs, thousands of years old, were still edible.",
    "A swift can stay airborne for ten months without landing, eating and sleeping on the wing.",
    "Sloths only come down from the tree to defecate, roughly once a week.",
    "Bees have five eyes: two large compound eyes and three simple ones on top of the head.",
    "Orcas are not whales in the strict sense. They are the largest members of the dolphin family.",
    "Chilli heat evolved to deter mammals but not birds, which spread the seeds unharmed.",
    "Squirrels sometimes pretend to bury nuts to fool anything watching them.",
    "Norway knighted a penguin. Sir Nils Olav lives at Edinburgh Zoo and holds a rank in the Norwegian King's Guard.",
    "Every tiger's stripe pattern is unique, and is used to identify individuals in the wild.",
    "Some bamboo species can be heard growing on a quiet night, creaking as they extend.",
    "Axolotls stay in their larval form for life and can regrow limbs, jaws and parts of the brain.",
    "Sharks existed before trees. They have been swimming for roughly 400 million years.",
    "There is a lake in Tanzania so alkaline it can calcify the bodies of animals that die in it.",
    "Bracken is one of the most widespread plants on Earth and has been around since before flowering plants.",
    "A coconut can float across an ocean and still germinate when it lands.",
    "Snow leopards cannot roar, and often drape their enormous tail over themselves like a scarf.",
    "Saffron is the most expensive spice by weight, because each flower yields three threads picked by hand.",
    "Some frogs freeze almost solid in winter and thaw back to life in spring.",
    "The blood of horseshoe crabs is blue and is used to test medicines for bacterial contamination.",
    "Bees are not native to Australia in the honeybee sense; the country has over 1,600 native bee species, most solitary.",
    "Sloths digest so slowly that a single leaf can take a month to pass through.",
    "Penguins propose with pebbles, offering the smoothest one they can find.",
    "The Portuguese man o' war is not one animal but a colony of organisms that cannot survive apart.",
    "There is a plant that smells of chocolate: the chocolate cosmos, from Mexico, extinct in the wild.",
    "A honeybee makes about a twelfth of a teaspoon of honey in her whole life.",
    "The Sargasso Sea has no coasts. It is defined entirely by the currents around it.",
    "Some spiders build decoy spiders out of debris, larger than themselves, to fool predators.",
    "Anglerfish males of some species fuse permanently to the female, dissolving into little more than a supply of sperm.",
    "Koalas sleep up to 20 hours a day because eucalyptus provides so little energy.",
    "A queen bee can lay up to 2,000 eggs a day.",
    "Barnacles are crustaceans that glue their own heads to a rock and then grow a shell.",
    "There is a species of beetle that can survive being run over by a car.",
    "The vanilla orchid's flower opens for a single day, which is why hand pollination is so laborious.",
    "A hippo can outrun a human on land.",
    "Leopard seals sing under the Antarctic ice, and each individual has its own repertoire.",
    "Tea was accidentally discovered, according to legend, when leaves blew into an emperor's pot of boiling water.",
    "Zebras are black with white stripes. The underlying skin is dark.",
    "Cleaner wrasse set up stations on reefs where much larger fish queue up to be picked clean.",
    "Snails have thousands of tiny teeth on a ribbon-like tongue called a radula.",
    "A dying tree can pass its carbon into the network, feeding neighbours and its own seedlings.",
    "Some spiders balloon, releasing silk to be carried on air currents for hundreds of kilometres.",
    "Flying fish can glide for up to 200 metres above the water.",
    "Slugs mate hanging from a rope of their own mucus.",
    "Bees can see ultraviolet, so many flowers have landing patterns invisible to us.",
    "A sea cucumber breathes through its rear end.",
    "Spider silk was used as crosshairs in early optical instruments.",
    "Bats are not blind. Many see well, and fruit bats rely on eyesight rather than echolocation.",
    "Butterflies taste with their feet.",
    "A whale shark's skin can be 15cm thick, the thickest of any animal.",
    "A single strand of spider silk is stronger than steel of the same thickness.",
    "A carrot was originally purple. Orange ones were selectively bred, most likely in the Netherlands.",
    "Naked mole rats live in colonies with a single breeding queen, like bees.",
    "Cats walk like camels and giraffes, moving both right legs then both left.",
    "Squirrels plant thousands of trees a year by forgetting where they buried acorns.",
    "The world's smallest mammal by mass is the bumblebee bat, weighing about two grams.",
    "Sea snakes can absorb some oxygen through their skin, letting them stay under far longer.",
    "A jumping spider can see in more colours than we can and judges distance by defocusing its own retina.",
    "Some seeds need fire to germinate, staying dormant in soil for decades until one comes.",
    "Lodgepole pine cones are sealed with resin that only melts in a fire.",
    "A gecko's foot sticks using millions of microscopic hairs and molecular attraction, not suction or glue.",
    "Some lizards detach their tail to escape, and the tail keeps twitching to hold attention.",
    "Some plants can hear. Evening primrose produces sweeter nectar when it detects the vibration of a bee's wings.",
    "Some sea slugs steal chloroplasts from algae and photosynthesise for months.",
    "There are more insects in one square mile of rural land than there are humans on Earth.",
    "Some species of bamboo flower only once every 60 to 130 years, and all plants of that species flower at once worldwide.",
    "A sperm whale's click is the loudest sound made by any animal, loud enough to be dangerous at close range.",
    "Zebra stripes appear to deter biting flies, which struggle to land on them.",
    "Owls can rotate their heads about 270 degrees.",
    "Almonds are seeds of a fruit related to the peach.",
    "Sloths can hold their breath longer than dolphins - up to about 40 minutes.",
    "Bats are the only mammals capable of true sustained flight.",
    "Bowhead whales may live over 200 years - harpoon points from the 1800s have been found in living ones.",
    "Sunflowers track the sun while growing, then settle facing east once mature.",
    "Cats have a third eyelid that sweeps across the eye.",
    "Cats headbutt you to deposit scent from glands on their face, marking you as theirs.",
    "Sea ice is fresh, not salty. Salt is expelled as the water freezes.",
    "Grapes explode when microwaved, producing a small burst of plasma.",
    "Cows produce more milk when listening to slow music.",
    "Some sponges filter thousands of litres of water a day.",
    "Hippos secrete a red oily fluid that works as sunscreen and an antiseptic.",
    "Some lichens grow less than a millimetre a year and are used to date rock surfaces.",
    "Rats laugh when tickled, at a pitch too high for us to hear.",
    "Bar-headed geese migrate over the Himalayas at altitudes where the air holds a third of the oxygen at sea level.",
    "The corpse flower blooms for about two days and smells of rotting meat to attract flies.",
    "Bees keep their hive at a steady 35 degrees by fanning their wings or shivering.",
    "Waves do not carry water forward. The water moves in circles while the energy travels.",
    "Polar bear fur is not white. Each hair is hollow and transparent, scattering light.",
    "The tallest tree on Earth is a coast redwood in California, over 115 metres.",
    "Frogs were the first land animals with vocal cords.",
    "Sea water is not blue because it reflects the sky. It absorbs red light and scatters blue.",
    "The heaviest recorded pumpkin weighed over a tonne.",
    "Cicadas of some broods spend 13 or 17 years underground, prime numbers that make it hard for predators to sync with them.",
    "Lobsters taste with their legs and chew with their stomachs.",
    "A pangolin's scales are made of keratin and it rolls into a ball no big cat can open.",
    "Lemons float and limes sink, because limes are denser.",
    "Some termite colonies have been continuously occupied for over two thousand years.",
    "The mantis shrimp punches fast enough to boil the water around its claw for an instant.",
    "A group of owls is called a parliament.",
    "Broccoli, cauliflower, kale, cabbage and Brussels sprouts are all the same species, bred into different shapes.",
    "Sea otters have the densest fur of any animal - up to a million hairs per square inch - because they have no blubber.",
    "The word 'dinosaur' means terrible lizard, and was coined in 1842.",
    "Bees must visit around two million flowers to make a pound of honey.",
    "A hummingbird weighs less than a coin, and eats roughly half its body weight in a day.",
    "The blue whale's heart is roughly the size of a small car.",
    "Monarch butterflies migrate thousands of kilometres over several generations - no individual makes the round trip.",
    "A sundew catches insects on sticky droplets that look like dew, then slowly folds around them.",
    "An urchin's five teeth are arranged in a structure called Aristotle's lantern, described by him over 2,000 years ago.",
    "An earthworm has five pairs of structures that work as hearts.",
    "Birds cannot taste capsaicin at all, which is why chilli-treated seed keeps squirrels off feeders.",
    "A group of flamingos is called a flamboyance.",
    "The Atlantic Ocean is getting wider by about 2.5cm a year.",
    "Kangaroos use their tail as a fifth limb, and it pushes harder than their front and back legs combined.",
    "There is a species of fungus that turns ants into zombies and steers them to a spot ideal for spreading spores.",
    "A group of jellyfish is called a smack.",
    "Peanuts are not nuts. They are legumes, related to peas and beans.",
    "The Darwin's bark spider spins webs that span rivers, with anchor lines up to 25 metres long.",
    "The deep sea is the largest habitat on Earth, and most of it has never been seen.",
    "Vanilla comes from an orchid, and outside its native Mexico it must be pollinated by hand.",
    "Earthworms can move several tonnes of soil per hectare per year, turning it over completely across decades.",
    "Deep sea anglerfish light comes from bacteria they farm in a lure.",
    "A koala's gut bacteria are passed from mother to joey, without which it cannot digest eucalyptus.",
    "A group of ferrets is called a business.",
    "Elephants appear to mourn their dead, returning to bones and handling them gently.",
    "Sea horses are the only species where the male carries and gives birth to the young.",
    "The colour orange was named after the fruit, not the other way round.",
    "Some birds sleep while flying, shutting down one hemisphere at a time.",
    "A tide is the ocean being pulled into two bulges, one towards the Moon and one away from it.",
    "Stick insects can reproduce without males for generations, producing only daughters.",
    "Bananas are berries. Strawberries, botanically speaking, are not.",
    "Some pythons incubate their eggs by shivering, generating heat with their own muscles.",
    "Sharks have no bones. Their skeletons are cartilage.",
    "Apples belong to the rose family, along with pears, cherries and strawberries.",
    "Meerkats take turns on sentry duty, and the one on watch eats last.",
    "Otters have a favourite rock they keep in a pouch of loose skin under the arm, for cracking shellfish.",
    "The pupil of a goat is rectangular, giving it a very wide field of view.",
    "Some acacias summon ants for defence, feeding and housing them in return for attacking anything that browses the leaves.",
    "Tardigrades survive vacuum, radiation and being frozen near absolute zero.",
    "Octopus blood is blue, because it carries oxygen with copper rather than iron.",
    "Trees talk to each other through fungal networks in the soil, sharing nutrients and warnings.",
    "An elephant's trunk has around 40,000 muscles.",
    "The Great Barrier Reef is visible from low Earth orbit, which the Great Wall of China is not.",
    "A New Caledonian crow will bend a wire into a hook without ever having seen one.",
    "Potatoes were the first vegetable grown in space.",
    "A Tasmanian devil has one of the strongest bites for its size of any mammal.",
    "Sea sponges have no brain, heart, or nervous system, and were among the first animals.",
    "Pineapples take about two years to grow a single fruit.",
    "A group of giraffes is called a tower.",
    "Whale falls create entire ecosystems on the sea floor that can last for decades.",
    "Some stick insect eggs survive being eaten by birds and hatch after passing through.",
    "Mushrooms are more closely related to animals than to plants.",
    "A red fox's pounce is far more successful when it jumps roughly north-east.",
    "Dolphins sleep with one half of the brain at a time, keeping one eye open.",
    "Bees can be trained to detect explosives by smell.",
    "Rhinos have poor eyesight and will charge at things that turn out to be trees.",
    "The temperature of the sand decides whether a turtle egg becomes male or female.",
    "Echidnas have no teeth and crush food between their tongue and the roof of their mouth.",
    "Onions make you cry because they release a gas that becomes a mild acid on contact with your eyes.",
    "Blue is the rarest colour in nature. Most blue animals are producing structural colour, not pigment.",
    "Humpback songs spread across an ocean like a hit record, with populations picking up each other's versions.",
    "Peregrine falcons reach over 300km/h in a dive, making them the fastest animal on Earth.",
    "Duckweed can double its population in under two days.",
    "An octopus can taste with its arms.",
    "The domestic cat's purr sits in a frequency range associated with bone healing.",
    "The unicorn was long believed real enough that medieval apothecaries sold 'unicorn horn' - usually narwhal tusk.",
    "Snakes smell with their tongues, delivering particles to a sensory organ on the roof of the mouth.",
    "Yeast is a fungus, and bread rises on the carbon dioxide it exhales.",
    "Some caterpillars completely liquefy inside the chrysalis before rebuilding as a butterfly.",
    "Sperm whales sleep vertically, in pods, drifting nose-up near the surface.",
    "The immortal-looking Great Basin bristlecone pines include trees over 4,800 years old, still alive.",
    "A poison dart frog raised in captivity is harmless. Its toxin comes from the insects it eats in the wild.",
    "Seagrass meadows store carbon far faster per hectare than rainforest does.",
    "A kangaroo cannot move its back legs independently on land, but can swim with them alternating.",
    "Tulip bulbs were briefly worth more than houses in 1630s Holland.",
    "Hummingbirds are the only birds that can fly backwards.",
    "There is a species of jellyfish, Turritopsis dohrnii, that can revert to an earlier life stage - effectively ageing backwards.",
    "Nettles sting with hollow hairs that snap off like tiny glass needles and inject an irritant.",
    "There are around 8 million known species on Earth, and most are thought to be undiscovered.",
    "Silk is produced by a caterpillar spinning a cocoon from a single unbroken thread up to a kilometre long.",
    "Prairie dogs have calls specific enough to describe the colour of a passing human's shirt.",
    "Chocolate is toxic to dogs because they metabolise theobromine far more slowly than we do.",
    "Snails can have both male and female organs, and two snails can fertilise each other at once.",
    "Whales sing in dialects that vary by population and change over the years.",
    "Elephants can hear one another over several kilometres using low rumbles below human hearing.",
    "Beavers' teeth are orange because of the iron in their enamel, which keeps them sharp.",
    "There is a species of ant that explodes on purpose to defend its colony.",
    "Cows have best friends and get measurably stressed when they are separated from them.",
    "The word 'avocado' comes from a Nahuatl word, ahuacatl.",
    "An albatross can glide for hours without flapping, sleeping on the wing.",
    "Nudibranchs steal the stinging cells from the jellyfish they eat and use them in their own defence.",
    "A sloth's fur hosts moths that live nowhere else.",
    "There are more trees on Earth than stars in the Milky Way.",
    "About three quarters of deep sea animals produce their own light.",
    "Some frogs carry their tadpoles on their back to a safe pool, one at a time.",
    "The baobab stores thousands of litres of water in its trunk.",
    "A group of crows is called a murder; a group of ravens, an unkindness.",
    "Otters are one of the few animals that use tools, and one of the few that appear to play for its own sake.",
    "Magpies can recognise themselves in a mirror, one of very few non-mammals that can.",
    "Bees sometimes get drunk on fermented nectar, and guard bees turn them away at the hive entrance.",
    "A shrimp's heart is in its head.",
    "Nutmeg is toxic in large doses and was once worth more than its weight in gold.",
    "Hummingbirds enter a state called torpor at night, dropping their body temperature to survive until morning.",
    "The world's largest living organism is a fungus in Oregon covering nearly 10 square kilometres.",
    "Beluga whales can change the shape of the melon on their forehead, and appear to use it to express themselves.",
    "The glass frog has translucent skin, and you can watch its heart beat through its belly.",
    "Cinnamon is the inner bark of a tree, cut away in strips and left to curl as it dries.",
    "An otter eats about a quarter of its body weight a day to stay warm.",
    "A single strand of a golden orb weaver's silk is strong enough that cloth has been woven from it."
  ];

  /* Which day of the year it is, in the reader's own timezone - the fact should
     turn over at their midnight, not UTC's. */
  function dayOfYear(date) {
    const d = date || new Date();
    const start = new Date(d.getFullYear(), 0, 0);
    return Math.floor((d - start) / 86400000);
  }

  function forDate(date) {
    if (!FACTS.length) return '';
    return FACTS[(dayOfYear(date) - 1 + FACTS.length) % FACTS.length];
  }

  function today() { return forDate(new Date()); }

  return { today: today, forDate: forDate, count: FACTS.length, dayOfYear: dayOfYear };
})();
